An example of producing a channel using the beam_network_ch_model module

In [13]:
import numpy as np
import torch
import os
import sys
import importlib
torch.set_default_dtype(torch.float64)
import matplotlib.pyplot as plt

# Get the current working directory
scripts_dir = os.getcwd()
# Go up two levels
project_root = os.path.abspath(os.path.join(scripts_dir, '..'))
sys.path.append(project_root)

import src.beam_network_ch_model
importlib.reload(src.beam_network_ch_model)
from src.beam_network_ch_model import Network, pair

In [14]:
#Setting Network Parameters
num_RX_ant = 2
num_TX_ant = 4
num_scatterers = torch.tensor([[1, 1], [1, 1]])
lam = 0.01
Ant_dist = 0.005
#Setting Locations
TX_locs = [torch.tensor([-10.0, 0.0], dtype=torch.float64), torch.tensor([0.0, 0.0], dtype=torch.float64)]
RX_locs = [torch.tensor([-10.0, -10.0], dtype=torch.float64), torch.tensor([0, -10.0], dtype=torch.float64)]
SC_locs = np.array([[torch.tensor([[-20.0, -5.0]], dtype=torch.float64), torch.tensor([[10.0, -5.0]], dtype=torch.float64)],
                     [torch.tensor([[-20.0, -5.0]], dtype=torch.float64), torch.tensor([[10.0, -5.0]], dtype=torch.float64)]])

In [15]:
N = Network()
N.num_RX_ant = num_RX_ant
N.num_TX_ant = num_TX_ant
N.num_scatterers = num_scatterers
N.lam = lam
N.Ant_dist = Ant_dist
N.TX_locs = TX_locs
N.RX_locs = RX_locs
N.SC_locs = SC_locs
N.rand_ph = 0

In [16]:
p = pair(N, 1, 1)

In [17]:
p.calculate_A(L = [torch.tensor(torch.pi/6), torch.tensor(torch.pi/6)])
# p.calculate_Br()

tensor([[0.1000+6.4283e-14j, 0.0000+0.0000e+00j],
        [0.0000+0.0000e+00j, 0.0445+4.3082e-03j]], dtype=torch.complex64)

In [18]:
p.calculate_Br()

tensor([[ 1.0000+0.0000j,  1.0000+0.0000j],
        [ 1.0000+0.0000j, -0.9455-0.3256j]], dtype=torch.complex64)

In [19]:
p.calculate_Bt()

tensor([[ 1.0000-0.0000j,  1.0000-0.0000j],
        [ 1.0000-0.0000j, -0.9455-0.3256j],
        [ 1.0000-0.0000j,  0.7879+0.6157j],
        [ 1.0000-0.0000j, -0.5445-0.8388j]], dtype=torch.complex64)